apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stress-recommendationservice-003
  namespace: chaos-testing
spec:
  mode: all
  selector:
    namespaces:
      - default
    labelSelectors:
      app: recommendationservice
  stressors:
    cpu:
      workers: 2
      load: 80
  duration: "3m"
